server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 201212416
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  table:
    auto: update
  model:
    pack: com.macro.mall.tiny.pojo
  database:
    type: mysql #数据库类型 目前只支持mysql
mybatis-plus:
    mapper-locations: classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
      map-underscore-to-camel-case: true # 该配置就是将带有下划线的表字段映射为驼峰格式的实体类属性
